export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const UPDATE_SUCCESS_USER = 'UPDATE_SUCCESS_USER';
export const UPDATE_FAILURE_USER = 'UPDATE_FAILURE_USER';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const UPLOAD_PROFILE_IMAGE = 'UPLOAD_PROFILE_IMAGE';
export const UPLOAD_PROFILE_IMAGE_REQUEST = 'UPLOAD_PROFILE_IMAGE_REQUEST';
export const UPLOAD_PROFILE_IMAGE_SUCCESS = 'UPLOAD_PROFILE_IMAGE_SUCCESS';
export const UPLOAD_PROFILE_IMAGE_FAILURE = 'UPLOAD_PROFILE_IMAGE_FAILURE';

export const GET_TAGS = 'GET_TAGS';
export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE';

export const GET_USER_PROPOSALS = 'GET_USER_PROPOSALS';
export const GET_USER_PROPOSALS_REQUEST = 'GET_USER_PROPOSALS_REQUEST';
export const GET_USER_PROPOSALS_SUCCESS = 'GET_USER_PROPOSALS_SUCCESS';
export const GET_USER_PROPOSALS_FAILURE = 'GET_USER_PROPOSALS_FAILURE';

export const GET_REVERSIM_TEAM = 'GET_REVERSIM_TEAM';
export const GET_REVERSIM_TEAM_REQUEST = 'GET_REVERSIM_TEAM_REQUEST';
export const GET_REVERSIM_TEAM_SUCCESS = 'GET_REVERSIM_TEAM_SUCCESS';
export const GET_REVERSIM_TEAM_FAILURE = 'GET_REVERSIM_TEAM_FAILURE';

export const GET_PROPOSALS = 'GET_PROPOSALS';
export const GET_PROPOSALS_REQUEST = 'GET_PROPOSALS_REQUEST';
export const GET_PROPOSALS_SUCCESS = 'GET_PROPOSALS_SUCCESS';
export const GET_PROPOSALS_FAILURE = 'GET_PROPOSALS_FAILURE';
export const GET_PROPOSAL = 'GET_PROPOSAL';
export const GET_PROPOSAL_REQUEST = 'GET_PROPOSAL_REQUEST';
export const GET_PROPOSAL_SUCCESS = 'GET_PROPOSAL_SUCCESS';
export const GET_PROPOSAL_FAILURE = 'GET_PROPOSAL_FAILURE';
export const ATTEND_SESSION = 'ATTEND_SESSION';
export const ATTEND_SESSION_REQUEST = 'ATTEND_SESSION_REQUEST';
export const ATTEND_SESSION_SUCCESS = 'ATTEND_SESSION_SUCCESS';
export const ATTEND_SESSION_FAILURE = 'ATTEND_SESSION_FAILURE';
export const CREATE_PROPOSAL_REQUEST = 'CREATE_PROPOSAL_REQUEST';
export const CREATE_PROPOSAL_SUCCESS = 'CREATE_PROPOSAL_SUCCESS';
export const CREATE_PROPOSAL_FAILURE = 'CREATE_PROPOSAL_FAILURE';
export const UPDATE_PROPOSAL_SUCCESS = 'UPDATE_PROPOSAL_SUCCESS';
export const UPDATE_PROPOSAL_FAILURE = 'UPDATE_PROPOSAL_FAILURE';
export const GET_RECOMMENDATIONS = 'GET_RECOMMENDATIONS';
export const GET_RECOMMENDATIONS_REQUEST = 'GET_RECOMMENDATIONS_REQUEST';
export const GET_RECOMMENDATIONS_SUCCESS = 'GET_RECOMMENDATIONS_SUCCESS';
export const GET_RECOMMENDATIONS_FAILURE = 'GET_RECOMMENDATIONS_FAILURE';

export const GET_REVERSIM_TWEETS = 'GET_REVERSIM_TWEETS';
export const GET_REVERSIM_TWEETS_REQUEST = 'GET_REVERSIM_TWEETS_REQUEST';
export const GET_REVERSIM_TWEETS_SUCCESS = 'GET_REVERSIM_TWEETS_SUCCESS';
export const GET_REVERSIM_TWEETS_FAILURE = 'GET_REVERSIM_TWEETS_FAILURE';
